---
title: "Getting started with the tumr package"
vignette: >
  %\VignetteIndexEntry{Quarto HTML Vignettes}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---

We should write a brief intro here for one of the data sets.

## melanoma2 data set

```{r}
library(tumr)
data("melanoma2")
```

#### Code for plot_mean()
```{r}
#| code-fold: true
plot_mean <- function(data, group, time, measure, id, stat = median, remove_na = FALSE){
  data_summary <- data |>
    dplyr::group_by({{group}}, {{time}}) |>
    dplyr::summarise(measure = stat({{measure}}, na.rm = remove_na), .groups = "drop_last") |>
    dplyr::ungroup()

  if (remove_na == TRUE){
    data_full <- data |>
      na.omit(data)
  } else {
    data_full <- data
  }

  ggplot2::ggplot() +
    ggplot2::geom_line(data = data_full,
                       ggplot2::aes(x = {{time}},
                                    y = {{measure}},
                                    group = {{id}},
                                    color = {{group}}),
                       alpha = 0.5)  +
    ggplot2::geom_line(data = data_summary,
                       ggplot2::aes(x = {{time}},
                                    y = measure,
                                    color = {{group}}),
                       linewidth = 1.2)

}
```

## Plotting the Mean vs the Median

```{r}
#| layout-ncol: 2
#| fig-width: 4
#| fig-height: 3.5
mel2 <- tumr(melanoma2, ID, Day, Volume, Treatment)
plot_mean(melanoma2, Treatment, Day, Volume, ID, stat = mean)
mel2 |>
  plot_median()
```

## Response Feature Analysis of melanoma2

```{r}
(rfeat_mel2 <- mel2 |>
              rfeat(comparison = "both"))
```


## rfeat plot

```{r}
plot(rfeat_mel2)
```


## Linear mixed model

```{r}
(lmm_mel2 <- mel2 |>
  lmm())
```

## summary of mixed model

```{r}
(emm_sum <- summary(lmm_mel2))
```


## Looking at different data sets

```{r}
breast_meta <- tumr(breast, ID, Week, Volume, Treatment)

plot_median(breast_meta)
breast_rfeat <- rfeat(breast_meta, comparison = "t.test")
plot(breast_rfeat)
breast_lmm <- lmm(breast_meta)
summary(breast_lmm)
```

```{r}
mel1_meta <- tumr(melanoma1, ID, Day, Volume, Treatment)

plot_median(mel1_meta)
(mel1_rfeat <- rfeat(mel1_meta, comparison = "both"))
plot(mel1_rfeat)
(mel1_lmm <- lmm(mel1_meta, log1p(Volume) ~ Treatment*Day + (Day | ID)))
summary(mel1_lmm)
```

```{r}
pros_meta <- tumr(prostate, ID, Age, BLI, Genotype)

plot_median(pros_meta)
(pros_rfeat <- rfeat(pros_meta, comparison = "both"))
plot(pros_rfeat)
(pros_lmm <- lmm(pros_meta))
summary(pros_lmm)
```


```{r}
#| echo: false
#| eval: false
model <- lmm_mel2$model_sum

pred <- ggeffects::ggpredict(model, terms = "Day")
plot(pred)

pred2 <- ggeffects::ggpredict(model, terms = c("Day", "Treatment"))
plot(pred2)

emm <- emmeans::emmeans(model, ~ "Treatment")
plot(emm)

plot(emm_sum$`slope of treatment over time`)

sjPlot::plot_model(model, type = "re")
sjPlot::plot_model(model, type = "est")
sjPlot::plot_model(model, type = "pred", terms = c("Day", "Treatment"))

#Diagnostics
sjPlot::plot_model(model, type = "diag")
```




