---
title: "tumr data sets"
format: 
  html:
    toc: true
    toc-depth: 3
---

```{r}
#| include: false
library(tumr)
```

## Introduction

Each dataset is presented with four plots:

- Parametric method (original scale)
- Parametric method (original scale; fold change) 
- Parametric method (log scale)
- Parametric method (log scale; fold change) 
 


## Another Melanoma Data Set, *melanoma1*

```{r}
#| echo: false
data(melanoma1)
melanoma1$months <- melanoma1$Day / (365/12)
mel1 <- tumr(melanoma1, ID, months, Volume, Treatment)
```

```{r}
#| layout-ncol: 2
#| fig-width: 4
#| fig-height: 3.5
plot(mel1, par = TRUE, fold = FALSE)
plot(mel1, par = TRUE, fold = TRUE)
```

```{r}
#| layout-ncol: 2
#| fig-width: 4
#| fig-height: 3.5
plot(mel1, par = TRUE, fold = FALSE) + ggplot2::scale_y_log10()
plot(mel1, par = TRUE, fold = TRUE) + ggplot2::scale_y_log10()
```


## Breast Cancer Data Set, *breast*

```{r}
#| echo: false
data(breast)
breast_meta <- tumr(breast, ID, Week, Volume, Treatment)
```


```{r}
#| layout-ncol: 2
#| fig-width: 4
#| fig-height: 3.5
plot(breast_meta, par = TRUE, fold = FALSE)
plot(breast_meta, par = TRUE, fold = TRUE)
```


```{r}
#| layout-ncol: 2
#| fig-width: 4
#| fig-height: 3.5
plot(breast_meta, par = TRUE, fold = FALSE) + ggplot2::scale_y_log10()
plot(breast_meta, par = TRUE, fold = TRUE) + ggplot2::scale_y_log10()
```


## Prostate Cancer Data Set, *prostate*

```{r}
#| echo: false
data(prostate)
pros_meta <- tumr(prostate, ID, Age, BLI, Genotype)
```



```{r}
#| layout-ncol: 2
#| fig-width: 4
#| fig-height: 3.5
plot(pros_meta, par = TRUE, fold = FALSE)
plot(pros_meta, par = TRUE, fold = TRUE)
```


```{r}
#| layout-ncol: 2
#| fig-width: 4
#| fig-height: 3.5
plot_median(pros_meta, par = TRUE, fold = FALSE) + ggplot2::scale_y_log10()
plot_median(pros_meta, par = TRUE, fold = TRUE) + ggplot2::scale_y_log10()
```